name: Github Actions for Docker
run-name: ${{ github.actor }} is integrating Docker

# Specifying under which circumstances this action will be performed
on:
  push:
    branches:
      - main
  pull_request:

# Specify the jobs to be performed for this workflow
jobs:
  build-image:
    name: Build Docker
    runs-on: ubuntu-latest
    steps:
      - name: Login to Dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Set up Buildx (caching support)
        uses: docker/setup-buildx-action@v3
      
      - name: Build on Docker
        uses: docker/build-push-action@v5
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: mhayne/httpenv-fork:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
