name: Github Actions for Docker
run-name: ${{ github.actor }} is integrating Docker

# Specifying under which circumstances this action will be performed
on:
  push:
    branches:
      - main
  pull_request:

# Specify the jobs to be performed for this workflow
jobs:
  build-image:
    name: Build Docker
    runs-on: ubuntu-latest
    steps:

      # Set up QEMU for multi-platform builds ie Intel, Arm, etc.
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # Log in to Dockerhub using credentials stored as repo secrets
      - name: Log in to Dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      # Must be included in order to use caching in the next step
      - name: Set up Buildx (caching support)
        uses: docker/setup-buildx-action@v3
      
      - name: Build on Docker
        uses: docker/build-push-action@v5
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: mhayne/httpenv-fork:latest
          cache-from: type=gha # Corresponds to Buildx step
          cache-to: type=gha,mode=max # Corresponds to Buildx step
          platforms: linux/amd64, linux/arm64, linux/arm/v7 # Corresponds to QEMU step 
